### PR TITLE
feature(upload): upload changelog within the action using PyGithub

### LINKED ISSUE #8: [enhancement] Is it more convenient to update changelog in this action using PyGithub?
I think it is more convinient to update changelog within the action by using PyGithub.

Are you interested in that feature? If so, I would be glad to contribute to this project.

### PR DESCRIPTION
**Pull request by BobAnkh**
## Description

Upload CHANGELOG.md to Github within the action by using PyGithub to call relevant API.

Fixes #8

## How Has This Been Tested?

Python script is linted by flake8 and is formatted by yapf.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Other information

Update documentation of inputs usage in README.md

Update workflow file in this repo to use the new action

I'm simply installing PyGithub with `RUN pip install PyGithub['integrations']`. I'm not sure if it is better to use requirements.txt for further enhancement.

### CODE REVIEW

**Comment by BobAnkh** [comment]
Workflow fails because this is a pr from forked repo where the GITHUB_TOKEN have only read permission to this repo.

@srepollock Please review it.

**Comment by srepollock** [comment]
I'm okay with the commits failing (I knew about the issue a while back) but why didn't you take out all the other references to the file creations in the python file? Looks like what I did is no longer necessary?

**Comment by BobAnkh** [comment]
> I'm okay with the commits failing (I knew about the issue a while back) but why didn't you take out all the other references to the file creations in the python file? Looks like what I did is no longer necessary?

Well, I didn't remove it because I thought this might be useful if you plan to implement features like `upload to assets` in the future.

So if you think file creation is no longer needed, I will remove it in the next commit along with deleting lines in the workflow file which I have commented.

**Comment by srepollock** [comment]
Thanks, this looks good then

**Review by srepollock — APPROVED** [review]

**Pull request merged**
